#!/usr/bin/env bash

export PATH=$PATH:/usr/local/bin

cd $HOME/src/trick_skel
if [ $? -ne 0 ]; then
    echo "can't cd to trick_skel, bailing out"
    exit
fi

TRICK_HOSTNAME=${HOSTNAME%%.*}

case $TRICK_HOSTNAME in
    sting|sam|ss|ro|huangniu|ll|SHN-7-L-170|salta|hg)
        if [ -e $HOME/.keychain/$HOSTNAME-sh ]; then
            . $HOME/.keychain/$HOSTNAME-sh
        fi
        svn up > /dev/null
        SVN_STAT=`svn stat`
        if [ "$SVN_STAT" != "" ]; then
            echo "Local modifications exist:"
            echo $SVN_STAT
            echo
        fi
        ;;
    survey-app01|dev-survey-app07|troy|futurebase-img01|atlas|ratchet)
        ./mintel/update-rsync.sh
        ;;
    *)
        echo "no update location set in cron-daily for hostname=${TRICK_HOSTNAME}, help me."
        ;;
esac

./install > /dev/null
