#!/bin/sh

atlas=172.17.6.14
export PATH=$PATH:/usr/local/bin

cd $HOME/src/trick_skel
if [ $? -ne 0 ]; then
    exit
fi

TRICK_HOSTNAME=`hostname -s`

case $TRICK_HOSTNAME in
    sting|mc|sam|atlas) svn up > /dev/null;;
    doobie|willow) rsync rsync://${atlas}/trick_skel/ . -a --del
esac

./install.sh > /dev/null
