process_names:
  - exe:
    - zoom
    - chrome
    - google-chrome
    - dcservice
    - dcondemand
    - activeDisplay
    - dcagentupgrader
    - dcconfig
    - dcfilescan
    - dcinventory
    - dcpatchscan
    - dcrdsagent
    - dcregister
