#!/bin/sh

VNC_TEMPLATE=$HOME/.trick_skel/view-icons/view_vnc_template.svg

if [ "`hostname`" = "mc.home.vanstaveren.us" ]; then
    cat $VNC_TEMPLATE | sed s:HOSTNAME:ed1:g > $HOME/.trick_skel/view-icons/view-vnc-ed:1.svg
fi
