#!/usr/bin/env bash

set -u
set -e

cd ~/Pictures/bg/

rm -f *png *jpg *jpeg # ugh this is getting stupid

for file in $(cat sources | grep -v "^#"); do
    wget -q -N $file || echo "Failed to fetch $file"
done

wget --quiet --reject "index.html*" --recursive --no-parent http://hg.vanstaveren.us/~trick/bg/
mv hg.vanstaveren.us/~trick/bg/* .
rm -rf hg.vanstaveren.us

rm -f *png # FIXME

for file in $(find -type f | grep -i -e "jpg\|jpeg"); do
    convert -scale 1920x1080 $file $file.png
done
