#!/usr/bin/env bash

if [ "$HOSTNAME" != "CHI-Linux-L-016" -a "$HOSTNAME" != "tink" -a "$HOSTNAME" != "compy386" ]; then
    echo "Not a gui host, skipping backgrounds."
    exit
fi

set -u
set -e

cd ~/Pictures/bg/

rm -f *png *jpg *jpeg # ugh this is getting stupid

wget --quiet --reject "index.html*" --recursive --no-parent http://hg.vanstaveren.us/~trick/bg/
mv hg.vanstaveren.us/~trick/bg/* .
rm -rf hg.vanstaveren.us

rm -f *png # FIXME

for file in $(find -type f | grep -i -e "jpg\|jpeg"); do
    convert -scale 1920x1080 $file $file.png
done
