#!/usr/bin/env bash

out=$HOME/.gnupg/gpg-agent.conf

echo "# trick_skel generated gpg-agent.conf $(strdate)" > $out
echo '# $Id$' >> $out

if [[ "$OSTYPE" == darwin* ]] && [ -x /opt/homebrew/bin/pinentry-mac ]; then
    echo "pinentry-program /opt/homebrew/bin/pinentry-mac" >> $out
else
    echo "pinentry-program $HOME/bin/trick_skel/my-pinentry" >> $out
fi
