#!/usr/bin/env bash

if [[ "$OSTYPE" == darwin* ]]; then
    exit 0
fi

cd $HOME/.config/i3status/

rm -f config

if [ -e config.$(hostname) ]; then
    ln -s config.$(hostname) config
else
    ln -s config.general config
fi
