#!/usr/bin/env bash

# from ssh config.d for thermostatpi:
## For the gpg-agent forward to work, I have to add this to /etc/ssh/sshd_config:
## StreamLocalBindUnlink yes
## then on the remote machine, init gpg:
## echo "keyserver hkp://keyserver.2ndquadrant.com:80" >> $HOME/.gnupg/gpg.conf
## gpg -k
## gpg --recv-key 0x01F8267F096D3F52
## wget https://raw.githubusercontent.com/trickv/trick_skel/master/.gnupg/0x01F8267F096D3F52-opengpg.gpg
## gpg -d 0x01F8267F096D3F52-opengpg.gpg

grep StreamLocalBindUnlink /etc/ssh/sshd_config &> /dev/null
if [ $? -ne 0 ]; then
    echo "***** Need to add StreamLocalBindUnlink yes to /etc/ssh/sshd_config"
    echo -e "\n#added by trick_skel bootstrap for gnupg forwarding\nStreamLocalBindUnlink yes" | sudo tee -a /etc/ssh/sshd_config
    echo "***** You now need to go restart sshd by hand..."
fi

gpg -k
gpg --recv-key 0x01F8267F096D3F52
