#!/usr/bin/env bash

echo "Bootstrap: $0"

DEST=$HOME/.trick_skel/sh-local/50-sh-local

which sudo &> /dev/null

if [ $? -eq 0 ]; then
    echo "alias \"su-\"=\"sudo su -\"" > $DEST
else
    echo "alias \"su-\"=\"echo -n 'su: '; su -\"" > $DEST
fi
