Host litecoin
    Hostname litecoin
    User trick
    PasswordAuthentication No
    RemoteForward /run/user/1000/gnupg/S.gpg-agent /run/user/1000/gnupg/S.gpg-agent.extra
    ForwardAgent Yes
    ProxyCommand ssh home.v9n.us -W %h:%p
    LocalForward 18789 127.0.0.1:18789
