#!/usr/bin/env bash

DEST=$HOME/.trick_skel/sh-local/50-sh-local

which sudo &> /dev/null

if [ $? -eq 0 ]; then
    echo "alias 'su-'='sudo su -'" > $DEST
else
    echo "alias 'su-'='su -'" > $DEST
fi
