#!/usr/bin/env bash

pathogenbundles[0]="https://github.com/airblade/vim-gitgutter.git"
pathogenbundles[1]="https://github.com/tpope/vim-surround.git"
pathogenbundles[2]="https://github.com/PProvost/vim-ps1"

which vim &> /dev/null
if [ $? -ne 0 ]; then
    echo "Package vim is missing! You should install it. I'm not installing vimrc."
    rm -rf $HOME/.vimrc $HOME/.vim
    cp optional/missing-vim $HOME/.trick_skel/sh-local/
    cat skel/.vimrc | grep -v mouse > $HOME/.vimrc
else
    if [ -d $HOME/.vim ]; then
        cp -R $HOME/.vim $HOME/tmp/trick_skel_backup/
    fi
    rm -rf $HOME/.vim
    cp -R skel/.vim $HOME
    for gitrepo in ${pathogenbundles[@]}; do
        echo "Cloning Git repo: "$gitrepo
        cd $HOME/.vim/bundle
        git clone $gitrepo
    done
    echo "Remember to remove this from install.d/70-dotvim-directory"
fi
