#!/usr/bin/env bash

packages=$(cat debian-workstation-packages)

if [ "$HOSTNAME" == "CHI-Linux-L-016" ]; then
    packages+=" "
    packages+=$(cat debian-workstation-packages-x11)
fi

echo $packages
sudo apt install $packages

pip3 install -r pip3-packages
