#!/usr/bin/env bash

packages=$(cat debian-workstation-packages)

case "$HOSTNAME" in
    "CHI-Linux-L-016" | "tink" | "compy386" | "CHI-LX-L-068" | "snoopy")
        packages+=" "
        packages+=$(cat debian-workstation-packages-x11)
        echo "Using x11 package set"
    ;;
    *)
        echo "Using base package set"
    ;;
esac

echo $packages
sudo apt install $packages

pip3 install -r pip3-packages
