#!/usr/bin/env perl

my $mintelUsProxyCommand = "connect -H proxy.usdmm.com:3128 %h %p";

# general use stuff
my %hosts = (
    'svn.gnome.org' => {
        'IdentityFile' => '~/.ssh/trickv@gnome.org/id_rsa',
        'User' => 'trickv'},
    'lish' => {
        'HostName' => 'lish.v9n.us',
        'User' => 'trickv'}
);

my @mintelHosts = qw(atlas diesel bigweld gasket anya willow doobie cartman baldrick raquel bbbx3 bbbx4);

$hostname = `hostname`;
print "# ssh config generated for $hostname\n";

# special cases for mc
if ($hostname =~ /mc.home.vanstaveren.us/) {
    foreach $cur (@mintelHosts) {
        $hosts{$cur} = {'User' => 'pv'};
    }
    $hosts{'atlas'}{'HostName'} = $ENV{'atlas'};

    $hosts{'atlas-vpn'} = {
        'HostName' => 'atlas.home.vanstaveren.us',
        'User' => 'pv' };
}

# special cases for atlas
if ($hostname =~ /atlas/) {
    for my $host ( keys %hosts ) {
        $hosts{$host}{'ProxyCommand'} = $mintelUsProxyCommand;
    }
}

# Read the hosts hash and output in a somewhat-standard format
while ( my ($hostname, $properties) = each(%hosts) ) {
    if ($hostname =~ /^$/) {
        $hostname = 'ERROR';
    }
    print "Host $hostname\n";
    while ( my ($property, $value) = each(%$properties) ) {
        if ($value =~ /^$/) {
            $value = 'ERROR';
        }
        print "    $property $value\n";
    }
}

