#!/usr/bin/env perl

use warnings;

my $mintelUsProxyCommand = "connect -S localhost:3129 %h %p";

# general use stuff
my %hosts = (
    '*' => {
        'ForwardX11' => 'yes'},
    'svn.gnome.org' => {
        'IdentityFile' => '~/.ssh/trickv@gnome.org/id_rsa',
        'User' => 'trickv'},
    'lish' => {
        'HostName' => 'lish.v9n.us',
        'User' => 'trickv'},
    'g1' => { 'User' => 'root' },
    'ci' => { 'User' => 'root' },
    'hg-lish' => {
        'User' => 'linode102280',
        'Hostname' => 'fremont398.linode.com',
    },
);

open (FILE, "optional/mintel_hosts") or die("Failed to open optional/mintel_hosts");
my @mintelHosts = <FILE>;
close (FILE);
chomp @mintelHosts;

my @mintelDotComHosts = qw(relay1.cn relay2.cn relay3.cn relay4.cn relay5.cn relay6.cn relay1.us relay2.us relay1.uk relay2.uk);
foreach $cur (@mintelDotComHosts) {
    push(@mintelHosts, "$cur.mintel.com");
}

my @shanghaiMintelHosts = qw(salta sentinel home elecktra daredevil huangniu);
foreach $cur (@shanghaiMintelHosts) {
    push(@mintelHosts, "$cur.shanghai.mintel.ad");
}

$hostname = `hostname`;
$hostname =~ s/\s+$//g;
my ($sec, $min, $hour, $mday, $mon, $year, $wday, $yday, $isdst) = localtime();
printf "# ssh config generated for $hostname at %4d-%02d-%02d %02d:%02d:%02d\n\n",
    $year + 1900, $mon + 1, $mday, $hour, $min, $sec;

# global stuff
print "# global settings\n";
print "PermitLocalCommand yes\n";
print "StrictHostKeyChecking no\n\n";

# special cases for home boxen
if ($hostname =~ /(?:mc|ed).home.vanstaveren.us/ or $hostname =~ /^ss$/) {
    my $mintelHostString;
    foreach $cur (@mintelHosts) {
        $hosts{$cur} = {'User' => 'pv'};
    }

    $hosts{'atlas'} = {
        'User' => 'pv' };
    $hosts{'atlas.home.vanstaveren.us'} = {
        'User' => 'pv' };
    $hosts{'survey-utils'} = {
        'User' => 'pv' };
}

# special cases for atlas
if ($hostname =~ /atlas/) {
    for my $host ( keys %hosts ) {
        $hosts{$host}{'ProxyCommand'} = $mintelUsProxyCommand;
    }
}

# Read the hosts hash and output in a somewhat-standard format
print "# per-host settings\n";
@sortedHosts = sort keys %hosts;
foreach $hostname (@sortedHosts) {
    $properties = $hosts{$hostname};
#while ( my ($hostname, $properties) = each(%hosts) ) {
    if ($hostname =~ /^$/) {
        $hostname = 'ERROR';
    }
    print "Host $hostname\n";
    while ( my ($property, $value) = each(%$properties) ) {
        if ($value =~ /^$/) {
            $value = 'ERROR';
        }
        print "    $property $value\n";
    }
}

