#!/usr/bin/env bash

. ~/.bash_profile_trick_skel

winUser='Patrick van Staveren'
domain=MINTELCHICAGO
skynet=`master_password`
nearFullScreen='1268x972'
londonVncEncoding=CoRRE

rdesktop=`which rdesktop`
vnc=`which vncviewer`

vncPasswords=$HOME/.vnc/passwords


lookup () {
    TFILE=`mktemp`

    HOST=`echo $1 | cut -d: -f1`
    VNC_DISPLAY=`echo $1 | cut -s -d: -f2`

    host $HOST 2> /dev/null > $TFILE
    if [ $? -eq 0 ]; then
        IP=`cat $TFILE | grep 'has address' | tail -n 1 | cut -d\  -f4`
        DOMAIN=`cat $TFILE | cut -d\  -f1 | cut -d. -f2-`
        return 0
    fi

    nmblookup $HOST 2> /dev/null > $TFILE
    cat $TFILE | tail -n 1 | grep failed &> /dev/null
    if [ $? -ne 0 ]; then
        IP=`cat $TFILE | tail -n 1 | cut -d\  -f1`
        return 0
    fi

    rm $TFILE
    return 1
}

custom_error_msg () {
    ERR_MSG="$@"
    which zenity &> /dev/null
    if [ $? -eq 0 ]; then
        zenity --error --text="${ERR_MSG}"
    else
        xmessage "${ERR_MSG}"
    fi
}

lookup $1
if [ $? -ne 0 ]; then
    ERR_MSG="Sorry, couldn't figure out who $1 is."
    custom_error_msg "${ERR_MSG}"
    exit 1
else
    echo "Found $HOST, IP=$IP, VNC_DISPLAY=$VNC_DISPLAY"
fi

case $1 in
op|opserver)
    case $2 in
        'rdp')
            $rdesktop -g $nearFullScreen -u "${winUser}" -d "$domain" -p $skynet op
            ;;
        'vnc')
            $vnc -passwd $vncPasswords/uk-win-admin -encodings $londonVncEncoding op
            ;;
        esac
    ;;
*)
    # If a display is specified, use it, else don't specify
    if [ "$VNC_DISPLAY" != "" ]; then
        CONNECT_HOST="$IP:$VNC_DISPLAY"
    else
        CONNECT_HOST=$IP
    fi

    # Set passwords for general domain use
    case $DOMAIN in
        home.vanstaveren.us)
            PASSWD_FILE=$vncPasswords/home.vanstaveren.us
            ;;
        usdmm.com)
            PASSWD_FILE=$vncPasswords/usdmm.com
            ;;
    esac

    # Override domain-set passwords on a hostname basis here:
    case $1 in
        unnilquadium)
            PASSWD_FILE=$vncPasswords/unnilquadium.mintelchicago
            ;;
    esac

    if [ "$PASSWD_FILE" != "" ]; then
        PASSWD_STRING="-passwd $PASSWD_FILE"
    fi

    cmd="$vnc $PASSWD_STRING $CONNECT_HOST"
    echo $cmd
    $cmd
    ;;
esac

#'zorro')
    # Melanie
#    $vnc -passwd $vncPasswords/puff3r 172.17.6.22
#    ;;
#'amsterdam')
#    # Courtney
#    $vnc -passwd $vncPasswords/puff3r 172.17.0.210
#    ;;
#'gadolinium')
#    # Michelle
#    $vnc -passwd $vncPasswords/puff3r 172.17.5.65
#esac

# Cara Cosentino = WOLVERINE
