#!/usr/bin/env bash

set -u

### Deal with scripts in bootstrap.d (used to be install.d)
scriptdir=$HOME/.yadm/bootstrap.d/
for script in $(find $scriptdir -type f -executable | sort); do
    echo "Bootstrap executing: $script"
    $script || echo "$script failed"
done
